/// Stealed from https://github.com/typst/typst/blob/main/crates/typst/src/symbols/symbol.rs
use phf::phf_map;
use std::fmt::{self, Debug};
use typst_math_macros::symbols;
use wasm_bindgen::prelude::wasm_bindgen;

#[derive(Debug, Clone)]
#[wasm_bindgen(getter_with_clone)]
pub struct Symbol {
    pub symbol: char,
    pub category: Category,
}

#[derive(Debug, Clone)]
#[wasm_bindgen]
pub enum Category {
    KEYWORD,
    OPERATOR,
    DEFAULT,
}
impl fmt::Display for Category {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        fmt::Debug::fmt(self, f)
    }
}

#[derive(Debug, Clone, Copy)]
#[wasm_bindgen]
pub enum Color {
    KEYWORD,
    NUMBER,
}

/// The list of general symbols.
pub const SYMBOLS: phf::Map<&str, Symbol> = symbols! {
// pub const SYMBOLS: &str = symbols! {
    // Control.
    wj: '\u{2060}'; DEFAULT,
    zwj: '\u{200D}'; DEFAULT,
    zwnj: '\u{200C}'; DEFAULT,
    zws: '\u{200B}'; DEFAULT,
    lrm: '\u{200E}'; DEFAULT,
    rlm: '\u{200F}'; DEFAULT,

    // Spaces.
    space: [
        ' '; DEFAULT,
        nobreak: '\u{A0}'; DEFAULT,
        nobreak.narrow: '\u{202F}'; DEFAULT,
        en: '\u{2002}'; DEFAULT,
        quad: '\u{2003}'; DEFAULT,
        third: '\u{2004}'; DEFAULT,
        quarter: '\u{2005}'; DEFAULT,
        sixth: '\u{2006}'; DEFAULT,
        med: '\u{205F}'; DEFAULT,
        fig: '\u{2007}'; DEFAULT,
        punct: '\u{2008}'; DEFAULT,
        thin: '\u{2009}'; DEFAULT,
        hair: '\u{200A}'; DEFAULT,
    ],

    // Delimiters.
    paren: [l: '('; DEFAULT, r: ')'; DEFAULT, t: '⏜'; DEFAULT, b: '⏝'; DEFAULT],
    brace: [l: '{'; DEFAULT, r: '}'; DEFAULT, t: '⏞'; DEFAULT, b: '⏟'; DEFAULT],
    bracket: [l: '['; DEFAULT, l.double: '⟦'; DEFAULT, r: ']'; DEFAULT, r.double: '⟧'; DEFAULT, t: '⎴'; DEFAULT, b: '⎵'; DEFAULT],
    shell: [l: '〔'; DEFAULT, r: '〕'; DEFAULT, t: '⏠'; DEFAULT, b: '⏡'; DEFAULT],
    bar: [v: '|'; DEFAULT, v.double: '‖'; DEFAULT, v.triple: '⦀'; DEFAULT, v.broken: '¦'; DEFAULT, v.circle: '⦶'; DEFAULT, h: '―'; DEFAULT],
    fence: [l: '⧘'; DEFAULT, l.double: '⧚'; DEFAULT, r: '⧙'; DEFAULT, r.double: '⧛'; DEFAULT, dotted: '⦙'; DEFAULT],
    angle: [
        '∠'; DEFAULT,
        l: '⟨'; DEFAULT,
        r: '⟩'; DEFAULT,
        l.double: '《'; DEFAULT,
        r.double: '》'; DEFAULT,
        acute: '⦟'; DEFAULT,
        arc: '∡'; DEFAULT,
        arc.rev: '⦛'; DEFAULT,
        rev: '⦣'; DEFAULT,
        right: '∟'; DEFAULT,
        right.rev: '⯾'; DEFAULT,
        right.arc: '⊾'; DEFAULT,
        right.dot: '⦝'; DEFAULT,
        right.sq: '⦜'; DEFAULT,
        spatial: '⟀'; DEFAULT,
        spheric: '∢'; DEFAULT,
        spheric.rev: '⦠'; DEFAULT,
        spheric.top: '⦡'; DEFAULT,
    ],

    // Punctuation.
    amp: ['&'; DEFAULT, inv: '⅋'; DEFAULT],
    ast: [
        op: '∗'; DEFAULT,
        basic: '*'; DEFAULT,
        low: '⁎'; DEFAULT,
        double: '⁑'; DEFAULT,
        triple: '⁂'; DEFAULT,
        small: '﹡'; DEFAULT,
        circle: '⊛'; DEFAULT,
        square: '⧆'; DEFAULT,
    ],
    at: '@'; DEFAULT,
    backslash: ['\\'; DEFAULT, circle: '⦸'; DEFAULT, not: '⧷'; DEFAULT],
    co: '℅'; DEFAULT,
    colon: [':'; DEFAULT, double: '∷'; DEFAULT, eq: '≔'; DEFAULT, double.eq: '⩴'; DEFAULT],
    comma: ','; DEFAULT,
    dagger: ['†'; DEFAULT, double: '‡'; DEFAULT],
    dash: [
        en: '–'; DEFAULT,
        em: '—'; DEFAULT,
        fig: '‒'; DEFAULT,
        wave: '〜'; DEFAULT,
        colon: '∹'; DEFAULT,
        circle: '⊝'; DEFAULT,
        wave.double: '〰'; DEFAULT,
    ],
    dot: [
        op: '⋅'; DEFAULT,
        basic: '.'; DEFAULT,
        c: '·'; DEFAULT,
        circle: '⊙'; DEFAULT,
        circle.big: '⨀'; DEFAULT,
        square: '⊡'; DEFAULT,
        double: '¨'; DEFAULT,
        triple: '\u{20db}'; DEFAULT,
        quad: '\u{20dc}'; DEFAULT,
    ],
    excl: ['!'; DEFAULT, double: '‼'; DEFAULT, inv: '¡'; DEFAULT, quest: '⁉'; DEFAULT],
    quest: ['?'; DEFAULT, double: '⁇'; DEFAULT, excl: '⁈'; DEFAULT, inv: '¿'; DEFAULT],
    interrobang: '‽'; DEFAULT,
    hash: '#'; DEFAULT,
    hyph: ['‐'; DEFAULT, minus: '\u{2D}'; DEFAULT, nobreak: '\u{2011}'; DEFAULT, point: '‧'; DEFAULT, soft: '\u{ad}'; DEFAULT],
    percent: '%'; DEFAULT,
    copyright: ['©'; DEFAULT, sound: '℗'; DEFAULT],
    permille: '‰'; DEFAULT,
    pilcrow: ['¶'; DEFAULT, rev: '⁋'; DEFAULT],
    section: '§'; DEFAULT,
    semi: [';'; DEFAULT, rev: '⁏'; DEFAULT],
    slash: ['/'; DEFAULT, double: '⫽'; DEFAULT, triple: '⫻'; DEFAULT, big: '\u{29f8}'; DEFAULT],
    dots: [h.c: '⋯'; DEFAULT, h: '…'; DEFAULT, v: '⋮'; DEFAULT, down: '⋱'; DEFAULT, up: '⋰'; DEFAULT],
    tilde: [
        op: '∼'; DEFAULT,
        basic: '~'; DEFAULT,
        dot: '⩪'; DEFAULT,
        eq: '≃'; DEFAULT,
        eq.not: '≄'; DEFAULT,
        eq.rev: '⋍'; DEFAULT,
        equiv: '≅'; DEFAULT,
        equiv.not: '≇'; DEFAULT,
        nequiv: '≆'; DEFAULT,
        not: '≁'; DEFAULT,
        rev: '∽'; DEFAULT,
        rev.equiv: '≌'; DEFAULT,
        triple: '≋'; DEFAULT,
    ],

    // Accents; DEFAULT, quotes; DEFAULT, and primes.
    acute: ['´'; DEFAULT, double: '˝'; DEFAULT],
    breve: '˘'; DEFAULT,
    caret: '‸'; DEFAULT,
    caron: 'ˇ'; DEFAULT,
    hat: '^'; DEFAULT,
    diaer: '¨'; DEFAULT,
    grave: '`'; DEFAULT,
    macron: '¯'; DEFAULT,
    quote: [
        double: '"'; DEFAULT,
        single: '\''; DEFAULT,
        l.double: '“'; DEFAULT,
        l.single: '‘'; DEFAULT,
        r.double: '”'; DEFAULT,
        r.single: '’'; DEFAULT,
        angle.l.double: '«'; DEFAULT,
        angle.l.single: '‹'; DEFAULT,
        angle.r.double: '»'; DEFAULT,
        angle.r.single: '›'; DEFAULT,
        high.double: '‟'; DEFAULT,
        high.single: '‛'; DEFAULT,
        low.double: '„'; DEFAULT,
        low.single: '‚'; DEFAULT,
    ],
    prime: [
        '′'; DEFAULT,
        rev: '‵'; DEFAULT,
        double: '″'; DEFAULT,
        double.rev: '‶'; DEFAULT,
        triple: '‴'; DEFAULT,
        triple.rev: '‷'; DEFAULT,
        quad: '⁗'; DEFAULT,
    ],

    // https://en.wikipedia.org/wiki/List_of_mathematical_symbols_by_subject
    // Arithmetic.
    plus: [
        '+'; DEFAULT,
        circle: '⊕'; DEFAULT,
        circle.arrow: '⟴'; DEFAULT,
        circle.big: '⨁'; DEFAULT,
        dot: '∔'; DEFAULT,
        minus: '±'; DEFAULT,
        small: '﹢'; DEFAULT,
        square: '⊞'; DEFAULT,
        triangle: '⨹'; DEFAULT,
    ],
    minus: [
        '−'; DEFAULT,
        circle: '⊖'; DEFAULT,
        dot: '∸'; DEFAULT,
        plus: '∓'; DEFAULT,
        square: '⊟'; DEFAULT,
        tilde: '≂'; DEFAULT,
        triangle: '⨺'; DEFAULT,
    ],
    div: ['÷'; DEFAULT, circle: '⨸'; DEFAULT],
    times: [
        '×'; DEFAULT,
        big: '⨉'; DEFAULT,
        circle: '⊗'; DEFAULT,
        circle.big: '⨂'; DEFAULT,
        div: '⋇'; DEFAULT,
        three.l: '⋋'; DEFAULT,
        three.r: '⋌'; DEFAULT,
        l: '⋉'; DEFAULT,
        r: '⋊'; DEFAULT,
        square: '⊠'; DEFAULT,
        triangle: '⨻'; DEFAULT,
    ],
    ratio: '∶'; DEFAULT,

    // Relations.
    eq: [
        '='; DEFAULT,
        star: '≛'; DEFAULT,
        circle: '⊜'; DEFAULT,
        colon: '≕'; DEFAULT,
        def: '≝'; DEFAULT,
        delta: '≜'; DEFAULT,
        equi: '≚'; DEFAULT,
        est: '≙'; DEFAULT,
        gt: '⋝'; DEFAULT,
        lt: '⋜'; DEFAULT,
        m: '≞'; DEFAULT,
        not: '≠'; DEFAULT,
        prec: '⋞'; DEFAULT,
        quest: '≟'; DEFAULT,
        small: '﹦'; DEFAULT,
        succ: '⋟'; DEFAULT,
        triple: '≡'; DEFAULT,
        quad: '≣'; DEFAULT,
    ],
    gt: [
        '>'; DEFAULT,
        circle: '⧁'; DEFAULT,
        curly: '≻'; DEFAULT,
        curly.approx: '⪸'; DEFAULT,
        curly.double: '⪼'; DEFAULT,
        curly.eq: '≽'; DEFAULT,
        curly.eq.not: '⋡'; DEFAULT,
        curly.equiv: '⪴'; DEFAULT,
        curly.napprox: '⪺'; DEFAULT,
        curly.nequiv: '⪶'; DEFAULT,
        curly.not: '⊁'; DEFAULT,
        curly.ntilde: '⋩'; DEFAULT,
        curly.tilde: '≿'; DEFAULT,
        dot: '⋗'; DEFAULT,
        approx: '⪆'; DEFAULT,
        double: '≫'; DEFAULT,
        eq: '≥'; DEFAULT,
        eq.slant: '⩾'; DEFAULT,
        eq.lt: '⋛'; DEFAULT,
        eq.not: '≱'; DEFAULT,
        equiv: '≧'; DEFAULT,
        lt: '≷'; DEFAULT,
        lt.not: '≹'; DEFAULT,
        napprox: '⪊'; DEFAULT,
        nequiv: '≩'; DEFAULT,
        not: '≯'; DEFAULT,
        ntilde: '⋧'; DEFAULT,
        small: '﹥'; DEFAULT,
        tilde: '≳'; DEFAULT,
        tilde.not: '≵'; DEFAULT,
        tri: '⊳'; DEFAULT,
        tri.eq: '⊵'; DEFAULT,
        tri.eq.not: '⋭'; DEFAULT,
        tri.not: '⋫'; DEFAULT,
        triple: '⋙'; DEFAULT,
        triple.nested: '⫸'; DEFAULT,
    ],
    lt: [
        '<'; DEFAULT,
        circle: '⧀'; DEFAULT,
        curly: '≺'; DEFAULT,
        curly.approx: '⪷'; DEFAULT,
        curly.double: '⪻'; DEFAULT,
        curly.eq: '≼'; DEFAULT,
        curly.eq.not: '⋠'; DEFAULT,
        curly.equiv: '⪳'; DEFAULT,
        curly.napprox: '⪹'; DEFAULT,
        curly.nequiv: '⪵'; DEFAULT,
        curly.not: '⊀'; DEFAULT,
        curly.ntilde: '⋨'; DEFAULT,
        curly.tilde: '≾'; DEFAULT,
        dot: '⋖'; DEFAULT,
        approx: '⪅'; DEFAULT,
        double: '≪'; DEFAULT,
        eq: '≤'; DEFAULT,
        eq.slant: '⩽' ; DEFAULT,
        eq.gt: '⋚'; DEFAULT,
        eq.not: '≰'; DEFAULT,
        equiv: '≦'; DEFAULT,
        gt: '≶'; DEFAULT,
        gt.not: '≸'; DEFAULT,
        napprox: '⪉'; DEFAULT,
        nequiv: '≨'; DEFAULT,
        not: '≮'; DEFAULT,
        ntilde: '⋦'; DEFAULT,
        small: '﹤'; DEFAULT,
        tilde: '≲'; DEFAULT,
        tilde.not: '≴'; DEFAULT,
        tri: '⊲'; DEFAULT,
        tri.eq: '⊴'; DEFAULT,
        tri.eq.not: '⋬'; DEFAULT,
        tri.not: '⋪'; DEFAULT,
        triple: '⋘'; DEFAULT,
        triple.nested: '⫷'; DEFAULT,
    ],
    approx: ['≈'; DEFAULT, eq: '≊'; DEFAULT, not: '≉'; DEFAULT],
    prec: [
        '≺'; DEFAULT,
        approx: '⪷'; DEFAULT,
        double: '⪻'; DEFAULT,
        eq: '≼'; DEFAULT,
        eq.not: '⋠'; DEFAULT,
        equiv: '⪳'; DEFAULT,
        napprox: '⪹'; DEFAULT,
        nequiv: '⪵'; DEFAULT,
        not: '⊀'; DEFAULT,
        ntilde: '⋨'; DEFAULT,
        tilde: '≾'; DEFAULT,
    ],
    succ: [
        '≻'; DEFAULT,
        approx: '⪸'; DEFAULT,
        double: '⪼'; DEFAULT,
        eq: '≽'; DEFAULT,
        eq.not: '⋡'; DEFAULT,
        equiv: '⪴'; DEFAULT,
        napprox: '⪺'; DEFAULT,
        nequiv: '⪶'; DEFAULT,
        not: '⊁'; DEFAULT,
        ntilde: '⋩'; DEFAULT,
        tilde: '≿'; DEFAULT,
    ],
    equiv: ['≡'; DEFAULT, not: '≢'; DEFAULT],
    prop: '∝'; DEFAULT,

    // Set theory.
    emptyset: ['∅'; DEFAULT, rev: '⦰'; DEFAULT],
    nothing: ['∅'; DEFAULT, rev: '⦰'; DEFAULT],
    without: '∖'; DEFAULT,
    complement: '∁'; DEFAULT,
    in: [
        '∈'; DEFAULT,
        not: '∉'; DEFAULT,
        rev: '∋'; DEFAULT,
        rev.not: '∌'; DEFAULT,
        rev.small: '∍'; DEFAULT,
        small: '∊'; DEFAULT,
    ],
    subset: [
        '⊂'; DEFAULT,
        dot: '⪽'; DEFAULT,
        double: '⋐'; DEFAULT,
        eq: '⊆'; DEFAULT,
        eq.not: '⊈'; DEFAULT,
        eq.sq: '⊑'; DEFAULT,
        eq.sq.not: '⋢'; DEFAULT,
        neq: '⊊'; DEFAULT,
        not: '⊄'; DEFAULT,
        sq: '⊏'; DEFAULT,
        sq.neq: '⋤'; DEFAULT,
    ],
    supset: [
        '⊃'; DEFAULT,
        dot: '⪾'; DEFAULT,
        double: '⋑'; DEFAULT,
        eq: '⊇'; DEFAULT,
        eq.not: '⊉'; DEFAULT,
        eq.sq: '⊒'; DEFAULT,
        eq.sq.not: '⋣'; DEFAULT,
        neq: '⊋'; DEFAULT,
        not: '⊅'; DEFAULT,
        sq: '⊐'; DEFAULT,
        sq.neq: '⋥'; DEFAULT,
    ],
    union: [
        '∪'; DEFAULT,
        arrow: '⊌'; DEFAULT,
        big: '⋃'; DEFAULT,
        dot: '⊍'; DEFAULT,
        dot.big: '⨃'; DEFAULT,
        double: '⋓'; DEFAULT,
        minus: '⩁'; DEFAULT,
        or: '⩅'; DEFAULT,
        plus: '⊎'; DEFAULT,
        plus.big: '⨄'; DEFAULT,
        sq: '⊔'; DEFAULT,
        sq.big: '⨆'; DEFAULT,
        sq.double: '⩏'; DEFAULT,
    ],
    sect: [
        '∩'; DEFAULT,
        and: '⩄'; DEFAULT,
        big: '⋂'; DEFAULT,
        dot: '⩀'; DEFAULT,
        double: '⋒'; DEFAULT,
        sq: '⊓'; DEFAULT,
        sq.big: '⨅'; DEFAULT,
        sq.double: '⩎'; DEFAULT,
    ],

    // Calculus.
    infinity: '∞'; DEFAULT,
    oo: '∞'; DEFAULT,
    diff: '∂'; DEFAULT, // Deprecation planned
    partial: '∂'; DEFAULT,
    gradient: '∇'; DEFAULT,
    nabla: '∇'; DEFAULT,
    sum: ['∑'; DEFAULT, integral: '⨋'; DEFAULT],
    product: ['∏'; DEFAULT, co: '∐'; DEFAULT],
    integral: [
        '∫'; DEFAULT,
        arrow.hook: '⨗'; DEFAULT,
        ccw: '⨑'; DEFAULT,
        cont: '∮'; DEFAULT,
        cont.ccw: '∳'; DEFAULT,
        cont.cw: '∲'; DEFAULT,
        cw: '∱'; DEFAULT,
        dash: '⨍'; DEFAULT,
        dash.double: '⨎'; DEFAULT,
        double: '∬'; DEFAULT,
        quad: '⨌'; DEFAULT,
        sect: '⨙'; DEFAULT,
        slash: '⨏'; DEFAULT,
        square: '⨖'; DEFAULT,
        surf: '∯'; DEFAULT,
        times: '⨘'; DEFAULT,
        triple: '∭'; DEFAULT,
        union: '⨚'; DEFAULT,
        vol: '∰'; DEFAULT,
    ],
    laplace: '∆'; DEFAULT,

    // Logic.
    forall: '∀'; KEYWORD,
    exists: ['∃'; DEFAULT, not: '∄'; DEFAULT],
    top: '⊤'; DEFAULT,
    bot: '⊥'; DEFAULT,
    not: '¬'; DEFAULT,
    and: ['∧'; DEFAULT, big: '⋀'; DEFAULT, curly: '⋏'; DEFAULT, dot: '⟑'; DEFAULT, double: '⩓'; DEFAULT],
    or: ['∨'; DEFAULT, big: '⋁'; DEFAULT, curly: '⋎'; DEFAULT, dot: '⟇'; DEFAULT, double: '⩔'; DEFAULT],
    xor: ['⊕'; DEFAULT, big: '⨁'; DEFAULT],
    models: '⊧'; DEFAULT,
    forces: ['⊩'; DEFAULT, not: '⊮'; DEFAULT],
    therefore: '∴'; DEFAULT,
    because: '∵'; DEFAULT,
    qed: '∎'; DEFAULT,

    // Function and category theory.
    compose: '∘'; DEFAULT,
    convolve: '∗'; DEFAULT,
    multimap: '⊸'; DEFAULT,

    // Number theory.
    divides: ['∣'; DEFAULT, not: '∤'; DEFAULT],

    // Algebra.
    wreath: '≀'; DEFAULT,

    // Geometry.
    parallel: ['∥'; DEFAULT, circle: '⦷'; DEFAULT, not: '∦'; DEFAULT],
    perp: ['⟂'; DEFAULT, circle: '⦹'; DEFAULT],

    // Miscellaneous Technical.
    diameter: '⌀'; DEFAULT,
    join: ['⨝'; DEFAULT, r: '⟖'; DEFAULT, l: '⟕'; DEFAULT, l.r: '⟗'; DEFAULT],
    degree: ['°'; DEFAULT, c: '℃'; DEFAULT, f: '℉'; DEFAULT],
    smash: '⨳'; DEFAULT,

    // Currency.
    bitcoin: '₿'; DEFAULT,
    dollar: '$'; DEFAULT,
    euro: '€'; DEFAULT,
    franc: '₣'; DEFAULT,
    lira: '₺'; DEFAULT,
    peso: '₱'; DEFAULT,
    pound: '£'; DEFAULT,
    ruble: '₽'; DEFAULT,
    rupee: '₹'; DEFAULT,
    won: '₩'; DEFAULT,
    yen: '¥'; DEFAULT,

    // Miscellaneous.
    ballot: ['☐'; DEFAULT, x: '☒'; DEFAULT],
    checkmark: ['✓'; DEFAULT, light: '🗸'; DEFAULT],
    floral: ['❦'; DEFAULT, l: '☙'; DEFAULT, r: '❧'; DEFAULT],
    notes: [up: '🎜'; DEFAULT, down: '🎝'; DEFAULT],
    refmark: '※'; DEFAULT,
    servicemark: '℠'; DEFAULT,
    maltese: '✠'; DEFAULT,
    suit: [
        club.filled: '♣'; DEFAULT,
        club.stroked: '♧'; DEFAULT,
        diamond.filled: '♦'; DEFAULT,
        diamond.stroked: '♢'; DEFAULT,
        heart.filled: '♥'; DEFAULT,
        heart.stroked: '♡'; DEFAULT,
        spade.filled: '♠'; DEFAULT,
        spade.stroked: '♤'; DEFAULT,
    ],

    // Shapes.
    bullet: '•'; DEFAULT,
    circle: [
        stroked: '○'; DEFAULT,
        stroked.tiny: '∘'; DEFAULT,
        stroked.small: '⚬'; DEFAULT,
        stroked.big: '◯'; DEFAULT,
        filled: '●'; DEFAULT,
        filled.tiny: '⦁'; DEFAULT,
        filled.small: '∙'; DEFAULT,
        filled.big: '⬤'; DEFAULT,
        dotted: '◌'; DEFAULT,
        nested: '⊚'; DEFAULT,
    ],
    ellipse: [
        stroked.h: '⬭'; DEFAULT,
        stroked.v: '⬯'; DEFAULT,
        filled.h: '⬬'; DEFAULT,
        filled.v: '⬮'; DEFAULT,
    ],
    triangle: [
        stroked.t: '△'; DEFAULT,
        stroked.b: '▽'; DEFAULT,
        stroked.r: '▷'; DEFAULT,
        stroked.l: '◁'; DEFAULT,
        stroked.bl: '◺'; DEFAULT,
        stroked.br: '◿'; DEFAULT,
        stroked.tl: '◸'; DEFAULT,
        stroked.tr: '◹'; DEFAULT,
        stroked.small.t: '▵'; DEFAULT,
        stroked.small.b: '▿'; DEFAULT,
        stroked.small.r: '▹'; DEFAULT,
        stroked.small.l: '◃'; DEFAULT,
        stroked.rounded: '🛆'; DEFAULT,
        stroked.nested: '⟁'; DEFAULT,
        stroked.dot: '◬'; DEFAULT,
        filled.t: '▲'; DEFAULT,
        filled.b: '▼'; DEFAULT,
        filled.r: '▶'; DEFAULT,
        filled.l: '◀'; DEFAULT,
        filled.bl: '◣'; DEFAULT,
        filled.br: '◢'; DEFAULT,
        filled.tl: '◤'; DEFAULT,
        filled.tr: '◥'; DEFAULT,
        filled.small.t: '▴'; DEFAULT,
        filled.small.b: '▾'; DEFAULT,
        filled.small.r: '▸'; DEFAULT,
        filled.small.l: '◂'; DEFAULT,
    ],
    square: [
        stroked: '□'; DEFAULT,
        stroked.tiny: '▫'; DEFAULT,
        stroked.small: '◽'; DEFAULT,
        stroked.medium: '◻'; DEFAULT,
        stroked.big: '⬜'; DEFAULT,
        stroked.dotted: '⬚'; DEFAULT,
        stroked.rounded: '▢'; DEFAULT,
        filled: '■'; DEFAULT,
        filled.tiny: '▪'; DEFAULT,
        filled.small: '◾'; DEFAULT,
        filled.medium: '◼'; DEFAULT,
        filled.big: '⬛'; DEFAULT,
    ],
    rect: [
        stroked.h: '▭'; DEFAULT,
        stroked.v: '▯'; DEFAULT,
        filled.h: '▬'; DEFAULT,
        filled.v: '▮'; DEFAULT,
    ],
    penta: [stroked: '⬠'; DEFAULT, filled: '⬟'; DEFAULT],
    hexa: [stroked: '⬡'; DEFAULT, filled: '⬢'; DEFAULT],
    diamond: [
        stroked: '◇'; DEFAULT,
        stroked.small: '⋄'; DEFAULT,
        stroked.medium: '⬦'; DEFAULT,
        stroked.dot: '⟐'; DEFAULT,
        filled: '◆'; DEFAULT,
        filled.medium: '⬥'; DEFAULT,
        filled.small: '⬩'; DEFAULT,
    ],
    lozenge: [
        stroked: '◊'; DEFAULT,
        stroked.small: '⬫'; DEFAULT,
        stroked.medium: '⬨'; DEFAULT,
        filled: '⧫'; DEFAULT,
        filled.small: '⬪'; DEFAULT,
        filled.medium: '⬧'; DEFAULT,
    ],
    parallelogram: [
        stroked: '▱'; DEFAULT,
        filled: '▰'; DEFAULT,
    ],
    star: [op: '⋆'; DEFAULT, stroked: '☆'; DEFAULT, filled: '★'; DEFAULT],

    // Arrows; DEFAULT, harpoons; DEFAULT, and tacks.
    arrow: [
        r: '→'; DEFAULT,
        r.long.bar: '⟼'; DEFAULT,
        r.bar: '↦'; DEFAULT,
        r.curve: '⤷'; DEFAULT,
        r.dashed: '⇢'; DEFAULT,
        r.dotted: '⤑'; DEFAULT,
        r.double: '⇒'; DEFAULT,
        r.double.bar: '⤇'; DEFAULT,
        r.double.long: '⟹'; DEFAULT,
        r.double.long.bar: '⟾'; DEFAULT,
        r.double.not: '⇏'; DEFAULT,
        r.filled: '➡'; DEFAULT,
        r.hook: '↪'; DEFAULT,
        r.long: '⟶'; DEFAULT,
        r.long.squiggly: '⟿'; DEFAULT,
        r.loop: '↬'; DEFAULT,
        r.not: '↛'; DEFAULT,
        r.quad: '⭆'; DEFAULT,
        r.squiggly: '⇝'; DEFAULT,
        r.stop: '⇥'; DEFAULT,
        r.stroked: '⇨'; DEFAULT,
        r.tail: '↣'; DEFAULT,
        r.tilde: '⥲'; DEFAULT,
        r.triple: '⇛'; DEFAULT,
        r.twohead.bar: '⤅'; DEFAULT,
        r.twohead: '↠'; DEFAULT,
        r.wave: '↝'; DEFAULT,
        l: '←'; DEFAULT,
        l.bar: '↤'; DEFAULT,
        l.curve: '⤶'; DEFAULT,
        l.dashed: '⇠'; DEFAULT,
        l.dotted: '⬸'; DEFAULT,
        l.double: '⇐'; DEFAULT,
        l.double.bar: '⤆'; DEFAULT,
        l.double.long: '⟸'; DEFAULT,
        l.double.long.bar: '⟽'; DEFAULT,
        l.double.not: '⇍'; DEFAULT,
        l.filled: '⬅'; DEFAULT,
        l.hook: '↩'; DEFAULT,
        l.long: '⟵'; DEFAULT,
        l.long.bar: '⟻'; DEFAULT,
        l.long.squiggly: '⬳'; DEFAULT,
        l.loop: '↫'; DEFAULT,
        l.not: '↚'; DEFAULT,
        l.quad: '⭅'; DEFAULT,
        l.squiggly: '⇜'; DEFAULT,
        l.stop: '⇤'; DEFAULT,
        l.stroked: '⇦'; DEFAULT,
        l.tail: '↢'; DEFAULT,
        l.tilde: '⭉'; DEFAULT,
        l.triple: '⇚'; DEFAULT,
        l.twohead.bar: '⬶'; DEFAULT,
        l.twohead: '↞'; DEFAULT,
        l.wave: '↜'; DEFAULT,
        t: '↑'; DEFAULT,
        t.bar: '↥'; DEFAULT,
        t.curve: '⤴'; DEFAULT,
        t.dashed: '⇡'; DEFAULT,
        t.double: '⇑'; DEFAULT,
        t.filled: '⬆'; DEFAULT,
        t.quad: '⟰'; DEFAULT,
        t.stop: '⤒'; DEFAULT,
        t.stroked: '⇧'; DEFAULT,
        t.triple: '⤊'; DEFAULT,
        t.twohead: '↟'; DEFAULT,
        b: '↓'; DEFAULT,
        b.bar: '↧'; DEFAULT,
        b.curve: '⤵'; DEFAULT,
        b.dashed: '⇣'; DEFAULT,
        b.double: '⇓'; DEFAULT,
        b.filled: '⬇'; DEFAULT,
        b.quad: '⟱'; DEFAULT,
        b.stop: '⤓'; DEFAULT,
        b.stroked: '⇩'; DEFAULT,
        b.triple: '⤋'; DEFAULT,
        b.twohead: '↡'; DEFAULT,
        l.r: '↔'; DEFAULT,
        l.r.double: '⇔'; DEFAULT,
        l.r.double.long: '⟺'; DEFAULT,
        l.r.double.not: '⇎'; DEFAULT,
        l.r.filled: '⬌'; DEFAULT,
        l.r.long: '⟷'; DEFAULT,
        l.r.not: '↮'; DEFAULT,
        l.r.stroked: '⬄'; DEFAULT,
        l.r.wave: '↭'; DEFAULT,
        t.b: '↕'; DEFAULT,
        t.b.double: '⇕'; DEFAULT,
        t.b.filled: '⬍'; DEFAULT,
        t.b.stroked: '⇳'; DEFAULT,
        tr: '↗'; DEFAULT,
        tr.double: '⇗'; DEFAULT,
        tr.filled: '⬈'; DEFAULT,
        tr.hook: '⤤'; DEFAULT,
        tr.stroked: '⬀'; DEFAULT,
        br: '↘'; DEFAULT,
        br.double: '⇘'; DEFAULT,
        br.filled: '⬊'; DEFAULT,
        br.hook: '⤥'; DEFAULT,
        br.stroked: '⬂'; DEFAULT,
        tl: '↖'; DEFAULT,
        tl.double: '⇖'; DEFAULT,
        tl.filled: '⬉'; DEFAULT,
        tl.hook: '⤣'; DEFAULT,
        tl.stroked: '⬁'; DEFAULT,
        bl: '↙'; DEFAULT,
        bl.double: '⇙'; DEFAULT,
        bl.filled: '⬋'; DEFAULT,
        bl.hook: '⤦'; DEFAULT,
        bl.stroked: '⬃'; DEFAULT,
        tl.br: '⤡'; DEFAULT,
        tr.bl: '⤢'; DEFAULT,
        ccw: '↺'; DEFAULT,
        ccw.half: '↶'; DEFAULT,
        cw: '↻'; DEFAULT,
        cw.half: '↷'; DEFAULT,
        zigzag: '↯'; DEFAULT,
    ],
    arrows: [
        rr: '⇉'; DEFAULT,
        ll: '⇇'; DEFAULT,
        tt: '⇈'; DEFAULT,
        bb: '⇊'; DEFAULT,
        lr: '⇆'; DEFAULT,
        lr.stop: '↹'; DEFAULT,
        rl: '⇄'; DEFAULT,
        tb: '⇅'; DEFAULT,
        bt: '⇵'; DEFAULT,
        rrr: '⇶'; DEFAULT,
        lll: '⬱'; DEFAULT,
    ],
    arrowhead: [
        t: '⌃'; DEFAULT,
        b: '⌄'; DEFAULT,
    ],
    harpoon: [
        rt: '⇀'; DEFAULT,
        rt.bar: '⥛'; DEFAULT,
        rt.stop: '⥓'; DEFAULT,
        rb: '⇁'; DEFAULT,
        rb.bar: '⥟'; DEFAULT,
        rb.stop: '⥗'; DEFAULT,
        lt: '↼'; DEFAULT,
        lt.bar: '⥚'; DEFAULT,
        lt.stop: '⥒'; DEFAULT,
        lb: '↽'; DEFAULT,
        lb.bar: '⥞'; DEFAULT,
        lb.stop: '⥖'; DEFAULT,
        tl: '↿'; DEFAULT,
        tl.bar: '⥠'; DEFAULT,
        tl.stop: '⥘'; DEFAULT,
        tr: '↾'; DEFAULT,
        tr.bar: '⥜'; DEFAULT,
        tr.stop: '⥔'; DEFAULT,
        bl: '⇃'; DEFAULT,
        bl.bar: '⥡'; DEFAULT,
        bl.stop: '⥙'; DEFAULT,
        br: '⇂'; DEFAULT,
        br.bar: '⥝'; DEFAULT,
        br.stop: '⥕'; DEFAULT,
        lt.rt: '⥎'; DEFAULT,
        lb.rb: '⥐'; DEFAULT,
        lb.rt: '⥋'; DEFAULT,
        lt.rb: '⥊'; DEFAULT,
        tl.bl: '⥑'; DEFAULT,
        tr.br: '⥏'; DEFAULT,
        tl.br: '⥍'; DEFAULT,
        tr.bl: '⥌'; DEFAULT,
    ],
    harpoons: [
        rtrb: '⥤'; DEFAULT,
        blbr: '⥥'; DEFAULT,
        bltr: '⥯'; DEFAULT,
        lbrb: '⥧'; DEFAULT,
        ltlb: '⥢'; DEFAULT,
        ltrb: '⇋'; DEFAULT,
        ltrt: '⥦'; DEFAULT,
        rblb: '⥩'; DEFAULT,
        rtlb: '⇌'; DEFAULT,
        rtlt: '⥨'; DEFAULT,
        tlbr: '⥮'; DEFAULT,
        tltr: '⥣'; DEFAULT,
    ],
    tack: [
        r: '⊢'; DEFAULT,
        r.not: '⊬'; DEFAULT,
        r.long: '⟝'; DEFAULT,
        r.short: '⊦'; DEFAULT,
        r.double: '⊨'; DEFAULT,
        r.double.not: '⊭'; DEFAULT,
        l: '⊣'; DEFAULT,
        l.long: '⟞'; DEFAULT,
        l.short: '⫞'; DEFAULT,
        l.double: '⫤'; DEFAULT,
        t: '⊥'; DEFAULT,
        t.big: '⟘'; DEFAULT,
        t.double: '⫫'; DEFAULT,
        t.short: '⫠'; DEFAULT,
        b: '⊤'; DEFAULT,
        b.big: '⟙'; DEFAULT,
        b.double: '⫪'; DEFAULT,
        b.short: '⫟'; DEFAULT,
        l.r: '⟛'; DEFAULT,
    ],

     // Lowercase Greek.
     alpha: 'α'; DEFAULT,
     beta: ['β'; DEFAULT, alt: 'ϐ'; DEFAULT],
     chi: 'χ'; DEFAULT,
     delta: 'δ'; DEFAULT,
     epsilon: ['ε'; DEFAULT, alt: 'ϵ'; DEFAULT],
     eta: 'η'; DEFAULT,
     gamma: 'γ'; DEFAULT,
     iota: 'ι'; DEFAULT,
     kai: 'ϗ'; DEFAULT,
     kappa: ['κ'; DEFAULT, alt: 'ϰ'; DEFAULT],
     lambda: 'λ'; DEFAULT,
     mu: 'μ'; DEFAULT,
     nu: 'ν'; DEFAULT,
     ohm: ['Ω'; DEFAULT, inv: '℧'; DEFAULT],
     omega: 'ω'; DEFAULT,
     omicron: 'ο'; DEFAULT,
     phi: ['φ'; DEFAULT, alt: 'ϕ'; DEFAULT],
     pi: ['π'; DEFAULT, alt: 'ϖ'; DEFAULT],
     psi: 'ψ'; DEFAULT,
     rho: ['ρ'; DEFAULT, alt: 'ϱ'; DEFAULT],
     sigma: ['σ'; DEFAULT, alt: 'ς'; DEFAULT],
     tau: 'τ'; DEFAULT,
     theta: ['θ'; DEFAULT, alt: 'ϑ'; DEFAULT],
     upsilon: 'υ'; DEFAULT,
     xi: 'ξ'; DEFAULT,
     zeta: 'ζ'; DEFAULT,

     // Uppercase Greek.
     Alpha: 'Α'; DEFAULT,
     Beta: 'Β'; DEFAULT,
     Chi: 'Χ'; DEFAULT,
     Delta: 'Δ'; DEFAULT,
     Epsilon: 'Ε'; DEFAULT,
     Eta: 'Η'; DEFAULT,
     Gamma: 'Γ'; DEFAULT,
     Iota: 'Ι'; DEFAULT,
     Kai: 'Ϗ'; DEFAULT,
     Kappa: 'Κ'; DEFAULT,
     Lambda: 'Λ'; DEFAULT,
     Mu: 'Μ'; DEFAULT,
     Nu: 'Ν'; DEFAULT,
     Omega: 'Ω'; DEFAULT,
     Omicron: 'Ο'; DEFAULT,
     Phi: 'Φ'; DEFAULT,
     Pi: 'Π'; DEFAULT,
     Psi: 'Ψ'; DEFAULT,
     Rho: 'Ρ'; DEFAULT,
     Sigma: 'Σ'; DEFAULT,
     Tau: 'Τ'; DEFAULT,
     Theta: 'Θ'; DEFAULT,
     Upsilon: 'Υ'; DEFAULT,
     Xi: 'Ξ'; DEFAULT,
     Zeta: 'Ζ'; DEFAULT,

     // Hebrew.
     aleph: 'א'; DEFAULT,
     alef: 'א'; DEFAULT,
     beth: 'ב'; DEFAULT,
     bet: 'ב'; DEFAULT,
     gimmel: 'ג'; DEFAULT,
     gimel: 'ג'; DEFAULT,
     daleth: 'ד'; DEFAULT,
     dalet: 'ד'; DEFAULT,
     shin: 'ש'; DEFAULT,

     // Double-struck.
     AA: '𝔸'; DEFAULT,
     BB: '𝔹'; DEFAULT,
     CC: 'ℂ'; DEFAULT,
     DD: '𝔻'; DEFAULT,
     EE: '𝔼'; DEFAULT,
     FF: '𝔽'; DEFAULT,
     GG: '𝔾'; DEFAULT,
     HH: 'ℍ'; DEFAULT,
     II: '𝕀'; DEFAULT,
     JJ: '𝕁'; DEFAULT,
     KK: '𝕂'; DEFAULT,
     LL: '𝕃'; DEFAULT,
     MM: '𝕄'; DEFAULT,
     NN: 'ℕ'; DEFAULT,
     OO: '𝕆'; DEFAULT,
     PP: 'ℙ'; DEFAULT,
     QQ: 'ℚ'; DEFAULT,
     RR: 'ℝ'; DEFAULT,
     SS: '𝕊'; DEFAULT,
     TT: '𝕋'; DEFAULT,
     UU: '𝕌'; DEFAULT,
     VV: '𝕍'; DEFAULT,
     WW: '𝕎'; DEFAULT,
     XX: '𝕏'; DEFAULT,
     YY: '𝕐'; DEFAULT,
     ZZ: 'ℤ'; DEFAULT,

     // Miscellaneous letter-likes.
     ell: 'ℓ'; DEFAULT,
     planck: ['ℎ'; DEFAULT, reduce: 'ℏ'; DEFAULT],
     angstrom: 'Å'; DEFAULT,
     kelvin: 'K'; DEFAULT,
     Re: 'ℜ'; DEFAULT,
     Im: 'ℑ'; DEFAULT,
     dotless: [i: '𝚤'; DEFAULT, j: '𝚥'; DEFAULT],
};
